-- HERE FOR COMPLETENESS SAKE.
-- DO NOT NEED TO RUN THIS SCRIPT IF CREATING DATABASE MANUALLY OR WITH DIFFERENT NAME.
-- IF CREATING MANUALLY, PLEASE CREATE WITH CHARACTER SET AND COLLATION AS SHOWN BELOW.

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

DROP DATABASE IF EXISTS `payroll_management_system`;
CREATE DATABASE `payroll_management_system` ENIGINE=innodb DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `payroll_management_system`;
